# Generated by Django 4.2.3 on 2023-07-27 09:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('topics', '0002_remove_topic_downvote_remove_topic_upvote_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='users_downvote',
            field=models.ManyToManyField(blank=True, related_name='users_downvote', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='topic',
            name='users_upvote',
            field=models.ManyToManyField(blank=True, related_name='users_upvote', to=settings.AUTH_USER_MODEL),
        ),
    ]
